-- SWIGGY ANALYSIS : 

-- Basic Analysis:

-- 1. What is the total number of orders?

select count(order_id) as Total_orders from orders ;

-- 2. What is the total revenue generated?

select sum(price * quantity) as Total_revenue from orders ;

-- 3. How many unique customers have placed orders?

select count(distinct(customer_id)) as Total_customer from orders ;

-- 4. What are the top 5 highest order amounts?

select dish_ordered , price * quantity as Total_amount from orders order by Total_amount desc limit 5 ;

-- 5. How many orders are “Cancelled” and how many are “Successful”?

select order_status , count(order_status) as Count_status from orders group by order_status ;


-- Intermediate Analysis:

-- 1. How many orders has each customer placed?

select c.customer_name, count(o.order_id) as Total_orders
from customers c 
join orders o 
on c.customer_id = o.customer_id 
group by c.customer_name ;

-- 2. Who are the top 5 customers based on the number of orders?

select c.customer_name, count(o.order_id) as Total_orders
from customers c 
join orders o 
on c.customer_id = o.customer_id 
group by c.customer_name order by Total_orders desc limit 5 ;

-- 3. What is the total revenue generated by each restaurant?

select r.restaurant_name , sum(o.price * o.quantity) as Total_revenue
from restaurants r 
join orders o 
on r.restaurant_id = o.restaurant_id
group by r.restaurant_name ;

-- 4. Which restaurant has received the highest number of orders?

select r.restaurant_name, count(o.order_id) as Total_orders
from restaurants r 
join orders o 
on r.restaurant_id = o.restaurant_id 
group by r.restaurant_name order by Total_orders desc limit 1 ;

-- 5. What is the average order amount per customer?

select c.customer_name, round(avg(o.price * o.quantity),2) as Average_price_per_customer
from customers c 
join orders o 
on c.customer_id = o.customer_id
group by c.customer_name ;


-- Advanced analysis:

-- 1. What is the peak order hour (hour with the highest number of orders)?

select hour(order_time) as Peak_hours , count(order_id) as Total_order from orders
group by Peak_hours order by Total_order desc limit 5 ;


-- 2. What is the average delivery time for all orders?

SELECT ROUND(avg(TIMESTAMPDIFF(MINUTE, order_time, delivery_time)),2) AS avg_delivery_time_minutes
FROM orders;


-- 3. Who are the top 3 delivery partners based on the number of deliveries?

select p.partner_name , count(o.order_id) as Total_orders_delivered 
from delivery_partners p 
join orders o 
on p.partner_id = o.delivery_partner_id 
group by p.partner_name order by Total_orders_delivered desc limit 3 ;

-- 4. How many orders were delivered late (delivery_time > expected_delivery_time)?

SELECT COUNT(*) AS late_orders
FROM orders
WHERE delivery_time > expected_delivery_time;

-- 5. Which day has the highest number of orders?

select date(order_time) as order_date , count(order_id) as Total_orders
from orders group by order_date order by Total_orders desc limit 1 ;